---
- name: Configure Package Management Server
  hosts: chocolatey
  vars:
    packages:
    - https://chocolatey.org/api/v2/package/chocolatey-core.extension/1.3.3
    - https://chocolatey.org/api/v2/package/Firefox/62.0

  tasks:
  - include_role:
      name: chocolatey_server
    vars:
      chocolatey_server_api: SuperSecretChocolateyAPIKey
  - name: Download packages
    win_get_url:
      url: "{{ item }}"
      dest: "{{ ansible_env['TEMP'] }}\\{{ item | win_basename }}.nupkg"
    with_items: "{{ packages }}"
  - name: Deploy packages
    win_command: "choco push {{ ansible_env['TEMP'] }}\\{{ item | win_basename }}.nupkg --source http://127.0.0.1/chocolatey --api-key=SuperSecretChocolateyAPIKey --force"
    with_items: "{{ packages }}"
