---
- name: Disable Windows Firewall
  hosts: Windows
  tasks:
  - name: Disable firewall for Domain, Public and Private profiles
    win_firewall:
      state: enabled
      profiles:
      - Domain
      - Private
      - Public
