---
- name: create snow with api
  hosts: all
  tasks:
  - name: create incident ticket
    uri:
      url: https://"{{ sn_instance }}.service-now.com/api/now/table/incident"
      method: POST
      user: "{{ sn_user }}"
      password: "{{ sn_pass }}"
      body:
        short_description: This is an API test
        severity: 3
        priority: 2
      force_basic_auth: yes
      status_code: 201
      body_format: json
    delegate_to: localhost
