---
- name: check for Installed Packaged
  hosts: windows
  tasks:
  - name: Check for installed packages
    win_shell: Get-WmiObject -class Win32_Product | Export-Csv -Path "c:\temp\{{ inventory_hostname }}.csv"
    register: products_installed
    
  - debug:
      var: products_installed
