- name: Install Firefox from local repository
  hosts: all
  vars:
    chocolatey_server: 10.10.10.174
    packages:
    - firefox
  tasks:
  - name: Install packages
    win_chocolatey:
      name: "{{ item }}"
      source: "http://{{ chocolatey_server }}/chocolatey"
    with_items: "{{ packages }}"
